graphql:
  servlet:
    mapping: /graphql
    enabled: true
  
server:
  port: 8881
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect