spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8880
  error:
    include-message: always

auth:
  graphql:
    url: http://localhost:8881/graphql